/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2024-01-02 17:19:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class author_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TAI_LIEU/CNPM/QLSACH/QLSACH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLSACH/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TAI_LIEU/CNPM/QLSACH/QLSACH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLSACH/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1646447839062L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>AUTHOR ADMIN</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" sizes=\"32x32\" />\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"app doan\">\r\n");
      out.write("		<div class=\"background_black\" id=\"background_black\">\r\n");
      out.write("			<!-- Xu cac button confirm -->\r\n");
      out.write("			<form action = \"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" method=\"post\" class=\"confirm_container remove_class bg-white\">\r\n");
      out.write("				<input type=\"hidden\" id = \"input_id_delete\" name=\"idAuthor\" value=\"1\">\r\n");
      out.write("				<div class=\"confirm_header text-white bg-primary\"\r\n");
      out.write("					style=\"padding: 10px; font-weight: 700\">\r\n");
      out.write("					<i class=\"fas fa-check-circle\" style=\"color: #47f764\"></i> Thông báo\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"confirm_content\"\r\n");
      out.write("					style=\"padding: 10px; text-align: center\">\r\n");
      out.write("					Bạn chắc chắn muốn xóa tác giả có id: <b>2</b> <b\r\n");
      out.write("						class=\"ten_can_xoa\">Nguyễn Đức Ngọc</b>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"confirm_buttons\">\r\n");
      out.write("					<button class=\"btn btn-success me-1 mb-2 btn_xacnhan\"\r\n");
      out.write("						style=\"margin: 0px 10px\" type=\"submit\">Xác Nhận\r\n");
      out.write("					</button>\r\n");
      out.write("					<button class=\"btn btn-danger me-1 mb-2 btn_huy_cancel\"\r\n");
      out.write("						style=\"margin: 0px 10px\" type=\"button\">Hủy\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- Ket thuc xoa tác giả -->\r\n");
      out.write("		<!-- Xu ly toast -->\r\n");
      out.write("		<div class=\"toast_class\"></div>\r\n");
      out.write("		<!-- Ket thuc xu ly toast -->\r\n");
      out.write("		<div id=\"sidebar\" class=\"active\">\r\n");
      out.write("			<div class=\"sidebar-wrapper active\">\r\n");
      out.write("				<div class=\"sidebar-header\">\r\n");
      out.write("					<div class=\"d-flex justify-content-between\">\r\n");
      out.write("						<div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" style=\"text-decoration: none\"\r\n");
      out.write("                  ><img\r\n");
      out.write("                    src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("                    style=\"height: 40px\"\r\n");
      out.write("                    alt=\"Logo\"\r\n");
      out.write("                    srcset=\"\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span style=\"font-size: 25px\">BOOKSTORE</span></a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-menu\">\r\n");
      out.write("					<ul class=\"menu\">\r\n");
      out.write("              <li class=\"sidebar-title\">Danh Mục Quản Lý</li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-chart-bar\"></i>\r\n");
      out.write("                  <span>Statistics</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                 <i class=\"fas fa-book\"></i>\r\n");
      out.write("                  <span>Books</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li\r\n");
      out.write("                class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\" class='sidebar-link'>\r\n");
      out.write("                    <i class=\"fas fa-cart-plus\"></i>\r\n");
      out.write("                    <span>Orders</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f12(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-feather\"></i>\r\n");
      out.write("                  <span>Review</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f13(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-user-circle\"></i>\r\n");
      out.write("                  <span>Customer</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item active\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f14(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-user-astronaut\"></i>\r\n");
      out.write("                  <span>Author</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f15(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-bookmark\"></i>\r\n");
      out.write("                  <span>Category</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f16(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-house-user\"></i>\r\n");
      out.write("                  <span>Publisher</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"sidebar-toggler btn x\">\r\n");
      out.write("					<i data-feather=\"x\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("			<div class=\"page-content\">\r\n");
      out.write("				<section class=\"row\">\r\n");
      out.write("					<div class=\"col-12 col-lg-12\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("								<div class=\"card\">\r\n");
      out.write("									<div class=\"card-body px-3 py-4-5\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-md-4\">\r\n");
      out.write("												<div class=\"stats-icon purple\">\r\n");
      out.write("													<i class=\"fas fa-money-bill-alt text-c-red f-18\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-8\">\r\n");
      out.write("												<h6 class=\"text-muted font-semibold\">Total Profit</h6>\r\n");
      out.write("												<h6 class=\"font-extrabold mb-0\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write(" đ</h6>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("								<div class=\"card\">\r\n");
      out.write("									<div class=\"card-body px-3 py-4-5\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-md-4\">\r\n");
      out.write("												<div class=\"stats-icon blue\">\r\n");
      out.write("													<i class=\"fas fa-database text-c-blue f-18\"></i>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-8\">\r\n");
      out.write("												<h6 class=\"text-muted font-semibold\">Total Oders</h6>\r\n");
      out.write("												<h6 class=\"font-extrabold mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total_orders}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("                  <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-body px-3 py-4-5\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <div class=\"stats-icon green\">\r\n");
      out.write("                            <i class=\"fas fa-dollar-sign text-c-green f-18\"></i>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <h6 class=\"text-muted font-semibold\">Total Users</h6>\r\n");
      out.write("                          <h6 class=\"font-extrabold mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total_users}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-6 col-lg-3 col-md-6\">\r\n");
      out.write("                  <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-body px-3 py-4-5\">\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                          <div class=\"stats-icon red\">\r\n");
      out.write("                            <i class=\"fas fa-user text-c-yellow f-18\"></i>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-8\">\r\n");
      out.write("                          <h6 class=\"text-muted font-semibold\">Login Info</h6>\r\n");
      out.write("                          <h6 class=\"font-extrabold mb-0\"><a href=\"");
      if (_jspx_meth_c_005furl_005f17(_jspx_page_context))
        return;
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a> | \r\n");
      out.write("                          	<span><a href=\"");
      if (_jspx_meth_c_005furl_005f18(_jspx_page_context))
        return;
      out.write("\">Logout</a></span>\r\n");
      out.write("                          </h6>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Phan tim kiem -->\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<div class=\"col-lg-12 stretch-card\" style=\"padding: 0\">\r\n");
      out.write("									<div class=\"card\">\r\n");
      out.write("										<div class=\"card-body\">\r\n");
      out.write("											<h4 class=\"card-title\" style=\"margin-bottom: 0 !important\">\r\n");
      out.write("												Tìm kiếm tác giả nhanh</h4>\r\n");
      out.write("											<form action=\"\" id=\"form_search_submit\">\r\n");
      out.write("												<div class=\"input-group\" style=\"padding: 10px 0px\">\r\n");
      out.write("													<input type=\"search\" class=\"form-control rounded\"\r\n");
      out.write("														placeholder=\"Search\" name=\"keyword\"\r\n");
      out.write("														aria-label=\"Search\" aria-describedby=\"search-addon\" />\r\n");
      out.write("													<button type=\"submit\" class=\"btn btn-outline-primary\">\r\n");
      out.write("														search</button>\r\n");
      out.write("												</div>\r\n");
      out.write("											</form>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- Ket thuc tim kiem  -->\r\n");
      out.write("\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<div class=\"col-lg-12 stretch-card\" style=\"padding: 0\">\r\n");
      out.write("									<div class=\"card\">\r\n");
      out.write("										<div class=\"card-body\">\r\n");
      out.write("											<div\r\n");
      out.write("												style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("												<h4 class=\"card-title\" style=\"margin-bottom: 0 !important\">\r\n");
      out.write("													Danh sách tác giả</h4>\r\n");
      out.write("												<div style=\"display: flex;\">\r\n");
      out.write("													<button id=\"info\" class=\"btn btn-success btn_add\">\r\n");
      out.write("														<i class=\"fas fa-plus\"></i> <span>Thêm Tác Giả</span>\r\n");
      out.write("													</button>\r\n");
      out.write("													<div class=\"form_add display_none\"\r\n");
      out.write("														style=\"margin-left: 20px;\">\r\n");
      out.write("														<form action=\"");
      if (_jspx_meth_c_005furl_005f19(_jspx_page_context))
        return;
      out.write("\" method=\"post\" style=\"display: flex;\">\r\n");
      out.write("															<input class=\"form-control\"\r\n");
      out.write("																name=\"authorName\" type=\"text\" value=\"\" id = \"input_add_author\"\r\n");
      out.write("																placeholder=\"VD: Nguyễn Đức Ngọc\">\r\n");
      out.write("															<button id = \"btn_add_submit\"  style=\"margin-left: 5px;\" type=\"submit\"\r\n");
      out.write("																class=\"btn btn-success btn_add_submit\">Thêm</button>\r\n");
      out.write("														</form>\r\n");
      out.write("													</div>\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"table-responsive pt-3\">\r\n");
      out.write("												<table class=\"table table-bordered text-center\">\r\n");
      out.write("													<thead>\r\n");
      out.write("														<tr>\r\n");
      out.write("															<th><a href=\"");
      if (_jspx_meth_c_005furl_005f20(_jspx_page_context))
        return;
      out.write("\">ID</a></th>\r\n");
      out.write("															<th style=\"width: 65%;\"><a href=\"");
      if (_jspx_meth_c_005furl_005f21(_jspx_page_context))
        return;
      out.write("\">Tên tác giả</a></th>\r\n");
      out.write("															<th>Thay Đổi</th>\r\n");
      out.write("														</tr>\r\n");
      out.write("													</thead>\r\n");
      out.write("													<tbody id = \"author_data\">\r\n");
      out.write("													\r\n");
      out.write("													");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("													</tbody>\r\n");
      out.write("												</table>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<!-- Xu ly phan trang -->\r\n");
      out.write("											<div class=\"container\"\r\n");
      out.write("												style=\"margin-top: 10px; display: flex; justify-content: center; align-items: center;\">\r\n");
      out.write("												<div>Số lượng: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("												<nav aria-label=\"Page navigation\">\r\n");
      out.write("													<ul class=\"pagination\" id=\"pagination\"\r\n");
      out.write("														style=\"margin: 0 20px;\"></ul>\r\n");
      out.write("												</nav>\r\n");
      out.write("											</div>\r\n");
      out.write("											<!-- Ket thuc xu ly phan trang -->\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form action=\"");
      if (_jspx_meth_c_005furl_005f23(_jspx_page_context))
        return;
      out.write("\" id = \"form_page\">\r\n");
      out.write("    		<input type=\"hidden\" value = \"1\" id = \"page_input\" name = \"page\">\r\n");
      out.write("    		<input type=\"hidden\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"order\">\r\n");
      out.write("    		<input type=\"hidden\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dirpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name = \"dir\">\r\n");
      out.write("    	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("      	var form_page = document.querySelector(\"#form_page\");\r\n");
      out.write("      	var page_input = document.querySelector(\"#page_input\");\r\n");
      out.write("      	console.log(form_page);\r\n");
      out.write("      	var currentpage = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("      	var pagesize = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagesize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("		var maxpage = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxpage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("    	$(function () {\r\n");
      out.write("        window.pagObj = $('#pagination').twbsPagination({\r\n");
      out.write("        	totalPages: maxpage,\r\n");
      out.write("            visiblePages: pagesize,\r\n");
      out.write("            startPage: currentpage,\r\n");
      out.write("            onPageClick: function (event, page) {\r\n");
      out.write("                if(currentpage !== page){\r\n");
      out.write("                  page_input.setAttribute(\"value\", page);\r\n");
      out.write("                  console.info(page + ' (from options)');\r\n");
      out.write("                  form_page.submit();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	function createToastHTML(message, type, color, icon){ //#47f764\r\n");
      out.write("    		var toast_class = document.querySelector(\".toast_class\");\r\n");
      out.write("    		var div = document.createElement(\"div\");\r\n");
      out.write("    		var html = \"<div class = 'toast_to_left' style='position:relative; height: 90px;margin-bottom: 10px;'>\"+\r\n");
      out.write("	    	    \"<div class='toast_container' style = 'border-left: 8px solid \"+color+\" !important;'>\"+\r\n");
      out.write("	            \"<i class='\"+icon+\" toast_icon' style = 'color: \"+color+\" !important;'></i>\"+\r\n");
      out.write("	            \"<div class='toast_content'>\"+\r\n");
      out.write("	              \"<span style='font-weight: 700; color: \"+color+\";'>\"+type+\"</span>\"+\r\n");
      out.write("	              \"<span class='toast_content_name' style='color: #656565'>\"+message+\"</span>\"+\r\n");
      out.write("	           \" </div>\"+\r\n");
      out.write("	            \"<div>\"+\r\n");
      out.write("	              \"<i class='fa fa-times toast_close' style='font-size: 20px; cursor: pointer; color: #656565'aria-hidden='true'></i>\"+\r\n");
      out.write("	            \"</div></div></div>\";\r\n");
      out.write("	            div.innerHTML = html;\r\n");
      out.write("            toast_class.appendChild(div);\r\n");
      out.write("	  		var toast_noi_dung = div.querySelector(\".toast_content_name\");\r\n");
      out.write("	  	    var toast_container = div.querySelector(\".toast_container\");\r\n");
      out.write("	  	    \r\n");
      out.write("  			setTimeout(() => {\r\n");
      out.write("  			    toast_container.classList.remove(\"toast_to_left\");\r\n");
      out.write("  			    toast_container.classList.add(\"toast_to_right\");\r\n");
      out.write("  			}, 2000);\r\n");
      out.write("  			\r\n");
      out.write("  			setTimeout(() => {\r\n");
      out.write("  			    div.remove();\r\n");
      out.write("  			}, 3000);\r\n");
      out.write("\r\n");
      out.write("			  	var toast_close = div.querySelector(\".toast_close\");\r\n");
      out.write("			  	console.log(toast_close);\r\n");
      out.write("			  	toast_close.addEventListener(\"click\", () => {\r\n");
      out.write("			    	div.remove();\r\n");
      out.write("			  	});\r\n");
      out.write("    	}\r\n");
      out.write("    \r\n");
      out.write("		  \r\n");
      out.write("    	  var btn_edit = document.querySelectorAll(\".btn_edit\");\r\n");
      out.write("		  var form_chinh_sua = document.querySelectorAll(\".form_chinh_sua\");\r\n");
      out.write("		  var input_form_control = document.querySelectorAll(\".class_input_edit\");\r\n");
      out.write("		  var toast_class = document.querySelector(\".toast_class\");\r\n");
      out.write("		  var btn_delete = document.querySelectorAll(\".btn_delete\");\r\n");
      out.write("		  var confirm_content = document.querySelector(\".confirm_content\");\r\n");
      out.write("		  var remove_class = document.querySelector(\".remove_class\");\r\n");
      out.write("		  var background_black = document.querySelector(\"#background_black\");\r\n");
      out.write("		  \r\n");
      out.write("		  input_form_control.forEach((element) => {\r\n");
      out.write("			  element.addEventListener('change', (e) => {\r\n");
      out.write("				  element.setAttribute(\"value\", e.target.value);\r\n");
      out.write("				  console.log(element);\r\n");
      out.write("			  })\r\n");
      out.write("		  })\r\n");
      out.write("		  \r\n");
      out.write("		  btn_edit.forEach(element => {\r\n");
      out.write("		    element.addEventListener(\"click\", () => {\r\n");
      out.write("		        var icon = element.children[0];\r\n");
      out.write("		        console.log(\"CLICK\");\r\n");
      out.write("		        var get_parent_element = element.parentElement.parentElement;\r\n");
      out.write("		        var ten_hien_thi = get_parent_element.querySelector(\".ten_hien_thi\");\r\n");
      out.write("		        var form_chinh_sua = get_parent_element.querySelector(\".form_chinh_sua\");\r\n");
      out.write("		        ten_hien_thi.classList.toggle(\"display_none\");\r\n");
      out.write("		        form_chinh_sua.classList.toggle(\"display_block\");\r\n");
      out.write("		        if (icon.className ===\"far fa-times-circle\"){\r\n");
      out.write("		            icon.className = \"far fa-edit\";\r\n");
      out.write("		            element.className = \"btn btn-warning m-1 btn_edit\";\r\n");
      out.write("		        }\r\n");
      out.write("		        else{\r\n");
      out.write("		            icon.className = \"far fa-times-circle\";\r\n");
      out.write("		            element.className = \"btn btn-info m-1 btn_edit\";\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		  \r\n");
      out.write("			btn_delete.forEach(element => {\r\n");
      out.write("			    element.addEventListener(\"click\", () => {\r\n");
      out.write("			    	console.log(element.children[0]);\r\n");
      out.write("			    	var id_delete = element.children[0].getAttribute(\"value\");\r\n");
      out.write("			        var ten_tacgia = element.children[0].getAttribute(\"tentacgia\");\r\n");
      out.write("			        $(\"#input_id_delete\").val(id_delete);\r\n");
      out.write("			        confirm_content.innerHTML = \"Bạn chắc chắn muốn xóa tác giả có ID = \"+id_delete+ \" <p><b>\"+ten_tacgia+\"</b></p>\";\r\n");
      out.write("			        background_black.style.display = \"block\";\r\n");
      out.write("			        remove_class.style.display = \"block\";\r\n");
      out.write("			    	})\r\n");
      out.write("			    })\r\n");
      out.write("			    \r\n");
      out.write("\r\n");
      out.write("				var btn_huy_cancel = document.querySelector(\".btn_huy_cancel\");\r\n");
      out.write("				btn_huy_cancel.addEventListener(\"click\", () => {\r\n");
      out.write("				    background_black.style.display = \"none\";\r\n");
      out.write("				    remove_class.style.display = \"none\";\r\n");
      out.write("				})\r\n");
      out.write("		\r\n");
      out.write("		  \r\n");
      out.write("					var btn_add = document.querySelector(\".btn_add\");\r\n");
      out.write("					var form_add = document.querySelector(\".form_add\");\r\n");
      out.write("					btn_add.addEventListener(\"click\", () => {\r\n");
      out.write("					  var fa_classname = btn_add.children[0];\r\n");
      out.write("					  var text_add = btn_add.children[1];\r\n");
      out.write("					  if (fa_classname.className === \"fas fa-plus\") {\r\n");
      out.write("					    fa_classname.className = \"far fa-times-circle\";\r\n");
      out.write("					    btn_add.className = \"btn btn-danger btn_add\";\r\n");
      out.write("					    text_add.innerHTML = \"Thoát\";\r\n");
      out.write("					  } else {\r\n");
      out.write("					    fa_classname.className = \"fas fa-plus\";\r\n");
      out.write("					    btn_add.className = \"btn btn-success btn_add\";\r\n");
      out.write("					    text_add.innerHTML = \"Thêm tác giả\";\r\n");
      out.write("					  }\r\n");
      out.write("					  form_add.classList.toggle(\"display_none\");\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("					var input_add_author = document.querySelector(\"#input_add_author\");\r\n");
      out.write("					input_add_author.addEventListener(\"change\", (e) => {\r\n");
      out.write("						input_add_author.setAttribute(\"value\", e.target.value);\r\n");
      out.write("					})\r\n");
      out.write("					\r\n");
      out.write("					// AJAX\r\n");
      out.write("			    	var result = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${add_result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			    	if(result != \"\"){\r\n");
      out.write("			    		if(result == '-1'){ // < 2 ky tu\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Tên tác giả phải từ 2 ký tự trở lên\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}else if(result == '0'){ // == 0 sai order_old\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Tên tác giả đã tồn tại trên hệ thống.\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}else if(result == '1'){\r\n");
      out.write("				    		// Toast thành công\r\n");
      out.write("					  		createToastHTML(\"Thêm tác giả thành công.\", \"SUCCESS\", \"#47f764\", \"fas fa-check-circle\");\r\n");
      out.write("				    	}else if(result == '2'){\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Thêm tác giả thất bại.\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}\r\n");
      out.write("			    	}\r\n");
      out.write("				    	\r\n");
      out.write("			    	var result = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit_result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			    	if(result != \"\"){\r\n");
      out.write("			    		if(result == '-1'){ // < 2 ky tu\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Tên tác giả phải từ 2 ký tự trở lên\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}else if(result == '0'){ // == 0 sai order_old\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Tên tác giả đã tồn tại trên hệ thống.\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}else if(result == '1'){\r\n");
      out.write("				    		// Toast thành công\r\n");
      out.write("					  		createToastHTML(\"Chỉnh sửa tên tác giả thành công.\", \"SUCCESS\", \"#47f764\", \"fas fa-check-circle\");\r\n");
      out.write("				    	}else if(result == '2'){\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Chỉnh sửa tên tác giả thất bại.\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}\r\n");
      out.write("			    	}\r\n");
      out.write("				    	\r\n");
      out.write("			    	var result = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delete_result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			    	if(result != \"\"){\r\n");
      out.write("				    	if(result == '0'){ // == 0 sai order_old\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Tác giả đã có sách trên hệ thống.\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}else if(result == '1'){\r\n");
      out.write("				    		// Toast thành công\r\n");
      out.write("					  		createToastHTML(\"Xóa tác giả thành công.\", \"SUCCESS\", \"#47f764\", \"fas fa-check-circle\");\r\n");
      out.write("				    	}else if(result == '2'){\r\n");
      out.write("				    		// Toast thất bại\r\n");
      out.write("					  		createToastHTML(\"Xóa tác giả thất bại.\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("				    	}\r\n");
      out.write("			    	}\r\n");
      out.write("			    	\r\n");
      out.write("			    	// COOKIE\r\n");
      out.write("			        document.documentElement.scrollTop = getCookie(\"ScrollY\");\r\n");
      out.write("\r\n");
      out.write("			         window.addEventListener(\"scroll\", () => {\r\n");
      out.write("			            var x = pageYOffset;\r\n");
      out.write("			            document.cookie = \"ScrollY=\"+x;\r\n");
      out.write("			         });\r\n");
      out.write("\r\n");
      out.write("			         function getCookie(cname) {\r\n");
      out.write("			            let name = cname + \"=\";\r\n");
      out.write("			            let decodedCookie = decodeURIComponent(document.cookie);\r\n");
      out.write("			            let ca = decodedCookie.split(';');\r\n");
      out.write("			            for(let i = 0; i <ca.length; i++) {\r\n");
      out.write("			                let c = ca[i];\r\n");
      out.write("			                while (c.charAt(0) == ' ') {\r\n");
      out.write("			                c = c.substring(1);\r\n");
      out.write("			                }\r\n");
      out.write("			                if (c.indexOf(name) == 0) {\r\n");
      out.write("			                return c.substring(name.length, c.length);\r\n");
      out.write("			                }\r\n");
      out.write("			            }\r\n");
      out.write("			            return \"\";\r\n");
      out.write("			        }\r\n");
      out.write("				  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"author_admin.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/admin/author.jsp(20,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/include/css/bootstrap.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/admin/author.jsp(21,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/include/css/toast.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/admin/author.jsp(22,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/include/css/app.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/admin/author.jsp(23,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/include/css/admin/author_admin.css");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/admin/author.jsp(24,27) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/images/favico.png");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/admin/author.jsp(26,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/include/js/jquery.twbsPagination.js");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/admin/author.jsp(33,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/admin/author/delete.htm");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/admin/author.jsp(63,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/admin/statistics.htm");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/admin/author.jsp(65,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/images/logo.png");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/admin/author.jsp(80,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/admin/statistics.htm");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /WEB-INF/views/admin/author.jsp(87,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/admin/book.htm");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /WEB-INF/views/admin/author.jsp(95,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/admin/order.htm");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent(null);
      // /WEB-INF/views/admin/author.jsp(102,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/admin/review.htm");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f13 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f13_reused = false;
    try {
      _jspx_th_c_005furl_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f13.setParent(null);
      // /WEB-INF/views/admin/author.jsp(109,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f13.setValue("/admin/customer.htm");
      int _jspx_eval_c_005furl_005f13 = _jspx_th_c_005furl_005f13.doStartTag();
      if (_jspx_th_c_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f13);
      _jspx_th_c_005furl_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f13, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f14 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f14_reused = false;
    try {
      _jspx_th_c_005furl_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f14.setParent(null);
      // /WEB-INF/views/admin/author.jsp(116,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f14.setValue("/admin/author.htm");
      int _jspx_eval_c_005furl_005f14 = _jspx_th_c_005furl_005f14.doStartTag();
      if (_jspx_th_c_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f14);
      _jspx_th_c_005furl_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f14, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f15 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f15_reused = false;
    try {
      _jspx_th_c_005furl_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f15.setParent(null);
      // /WEB-INF/views/admin/author.jsp(123,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f15.setValue("/admin/category.htm");
      int _jspx_eval_c_005furl_005f15 = _jspx_th_c_005furl_005f15.doStartTag();
      if (_jspx_th_c_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f15);
      _jspx_th_c_005furl_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f15, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f16 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f16_reused = false;
    try {
      _jspx_th_c_005furl_005f16.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f16.setParent(null);
      // /WEB-INF/views/admin/author.jsp(130,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f16.setValue("/admin/publisher.htm");
      int _jspx_eval_c_005furl_005f16 = _jspx_th_c_005furl_005f16.doStartTag();
      if (_jspx_th_c_005furl_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f16);
      _jspx_th_c_005furl_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f16, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f16_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/admin/author.jsp(158,44) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      // /WEB-INF/views/admin/author.jsp(158,44) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("##,###");
      // /WEB-INF/views/admin/author.jsp(158,44) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total_profit}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f17 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f17_reused = false;
    try {
      _jspx_th_c_005furl_005f17.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f17.setParent(null);
      // /WEB-INF/views/admin/author.jsp(209,67) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f17.setValue("/account/login.htm");
      int _jspx_eval_c_005furl_005f17 = _jspx_th_c_005furl_005f17.doStartTag();
      if (_jspx_th_c_005furl_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f17);
      _jspx_th_c_005furl_005f17_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f17, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f17_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f18 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f18_reused = false;
    try {
      _jspx_th_c_005furl_005f18.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f18.setParent(null);
      // /WEB-INF/views/admin/author.jsp(210,42) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f18.setValue("/account/logout.htm");
      int _jspx_eval_c_005furl_005f18 = _jspx_th_c_005furl_005f18.doStartTag();
      if (_jspx_th_c_005furl_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f18);
      _jspx_th_c_005furl_005f18_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f18, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f18_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f19 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f19_reused = false;
    try {
      _jspx_th_c_005furl_005f19.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f19.setParent(null);
      // /WEB-INF/views/admin/author.jsp(259,28) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f19.setValue("/admin/author/add.htm");
      int _jspx_eval_c_005furl_005f19 = _jspx_th_c_005furl_005f19.doStartTag();
      if (_jspx_th_c_005furl_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f19);
      _jspx_th_c_005furl_005f19_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f19, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f19_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f20 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f20_reused = false;
    try {
      _jspx_th_c_005furl_005f20.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f20.setParent(null);
      // /WEB-INF/views/admin/author.jsp(277,28) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f20.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/admin/author.htm?page=${currentpage}&order=id&dir=${orderLink}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f20 = _jspx_th_c_005furl_005f20.doStartTag();
      if (_jspx_th_c_005furl_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f20);
      _jspx_th_c_005furl_005f20_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f20, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f20_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f21 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f21_reused = false;
    try {
      _jspx_th_c_005furl_005f21.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f21.setParent(null);
      // /WEB-INF/views/admin/author.jsp(278,48) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f21.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/admin/author.htm?page=${currentpage}&order=name&dir=${orderLink}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f21 = _jspx_th_c_005furl_005f21.doStartTag();
      if (_jspx_th_c_005furl_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f21);
      _jspx_th_c_005furl_005f21_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f21, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f21_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/author.jsp(284,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/admin/author.jsp(284,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/author.jsp(284,13) '${authors}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${authors}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("														<tr class=\"table-white\">\r\n");
            out.write("															<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id_author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("															<td><span class=\"ten_hien_thi\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.author_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("																<div class=\"form_chinh_sua display_none\">\r\n");
            out.write("																	<form action=\"");
            if (_jspx_meth_c_005furl_005f22(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\" method=\"post\" style=\"display: flex;\">\r\n");
            out.write("																		<input type=\"hidden\" name=\"idAuthor\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id_author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("																		<input class=\"form-control class_input_edit\"\r\n");
            out.write("																			name=\"authorName\" type=\"text\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.author_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("																		<button style=\"margin-left: 10px;\" type=\"submit\"\r\n");
            out.write("																			class=\"btn btn-success btn_edit_submit\">Sửa</button>\r\n");
            out.write("																	</form>\r\n");
            out.write("																</div></td>\r\n");
            out.write("															<td class=\"align-middle text-center\">\r\n");
            out.write("																<button type=\"button\"\r\n");
            out.write("																	class=\"btn btn-warning m-1 btn_edit\">\r\n");
            out.write("																	<i class=\"far fa-edit\"></i>\r\n");
            out.write("																</button>\r\n");
            out.write("																<button type=\"button\" class=\"btn btn-danger btn_delete\">\r\n");
            out.write("																	<input type = \"hidden\" name = \"idAuthor\" value = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id_author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("																		tentacgia = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.author_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("																		<i style=\"color: white\" class=\"fa fa-trash-alt\"></i>\r\n");
            out.write("																</button>\r\n");
            out.write("															</td>\r\n");
            out.write("														</tr>\r\n");
            out.write("													");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f22(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f22 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f22_reused = false;
    try {
      _jspx_th_c_005furl_005f22.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f22.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/admin/author.jsp(289,31) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f22.setValue("/admin/author/edit.htm");
      int _jspx_eval_c_005furl_005f22 = _jspx_th_c_005furl_005f22.doStartTag();
      if (_jspx_th_c_005furl_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f22);
      _jspx_th_c_005furl_005f22_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f22, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f22_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f23(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f23 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f23_reused = false;
    try {
      _jspx_th_c_005furl_005f23.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f23.setParent(null);
      // /WEB-INF/views/admin/author.jsp(334,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f23.setValue("/admin/author.htm");
      int _jspx_eval_c_005furl_005f23 = _jspx_th_c_005furl_005f23.doStartTag();
      if (_jspx_th_c_005furl_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f23);
      _jspx_th_c_005furl_005f23_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f23, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f23_reused);
    }
    return false;
  }
}
