/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2024-01-02 17:19:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TAI_LIEU/CNPM/QLSACH/QLSACH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLSACH/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Desktop/TAI_LIEU/CNPM/QLSACH/QLSACH/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QLSACH/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1646447839062L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Thông tin giỏ hàng</title>\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"\r\n");
      out.write("    />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" sizes=\"32x32\" />\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"app\">\r\n");
      out.write("      <div class=\"background_black\" id=\"background_black\">\r\n");
      out.write("        <!-- Xu cac button confirm -->\r\n");
      out.write("        <div class=\"confirm_container remove_class bg-white\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"confirm_header text-white bg-primary\"\r\n");
      out.write("            style=\"padding: 10px; font-weight: 700\"\r\n");
      out.write("          >\r\n");
      out.write("            <i class=\"fas fa-check-circle\" style=\"color: #47f764\"></i>\r\n");
      out.write("            Thông báo\r\n");
      out.write("          </div>\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"confirm_content\"\r\n");
      out.write("            style=\"padding: 10px; text-align: center\"\r\n");
      out.write("          >\r\n");
      out.write("            Bạn chắc chắn muốn xóa sách có id: <b>2</b>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"confirm_buttons\">\r\n");
      out.write("            <button\r\n");
      out.write("              class=\"btn btn-success me-1 mb-2 btn_xacnhan_xoa\"\r\n");
      out.write("              style=\"margin: 0px 10px\"\r\n");
      out.write("              type=\"button\"\r\n");
      out.write("            >\r\n");
      out.write("              <a href=\"#\" class=\"set_link\" style=\"text-decoration: none; color: white;\">Xác Nhận</a>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("              class=\"btn btn-danger me-1 mb-2 btn_huy_cancel\"\r\n");
      out.write("              style=\"margin: 0px 10px\"\r\n");
      out.write("              type=\"button\"\r\n");
      out.write("            >\r\n");
      out.write("              Hủy\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Ket thuc xu ly xoa book -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Xu ly toast -->\r\n");
      out.write("      <div class=\"toast_class\"></div>\r\n");
      out.write("      <!-- Ket thuc xu ly toast -->\r\n");
      out.write("      <div id=\"sidebar\" class=\"active\">\r\n");
      out.write("        <div class=\"sidebar-wrapper active\">\r\n");
      out.write("          <div class=\"sidebar-header\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between\">\r\n");
      out.write("              <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" style=\"text-decoration: none\"\r\n");
      out.write("                  ><img\r\n");
      out.write("                    src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("                    style=\"height: 40px\"\r\n");
      out.write("                    alt=\"Logo\"\r\n");
      out.write("                    srcset=\"\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <span style=\"font-size: 25px\">BOOKSTORE</span></a\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sidebar-menu\">\r\n");
      out.write("            <ul class=\"menu\">\r\n");
      out.write("              <li class=\"sidebar-title\">Danh Mục Khách Hàng</li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                  <i class=\"fas fa-chart-bar\"></i>\r\n");
      out.write("                  <span>Thông tin tài khoản</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"sidebar-item active\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\" class=\"sidebar-link\">\r\n");
      out.write("                 <i class=\"fas fa-book\"></i>\r\n");
      out.write("                  <span>Giỏ hàng</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li\r\n");
      out.write("                class=\"sidebar-item\">\r\n");
      out.write("                <a href=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\" class='sidebar-link'>\r\n");
      out.write("                    <i class=\"fas fa-cart-plus\"></i>\r\n");
      out.write("                    <span>Danh sách đơn hàng</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <button class=\"sidebar-toggler btn x\">\r\n");
      out.write("            <i data-feather=\"x\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"main\">\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("          <section class=\"row\">\r\n");
      out.write("            <div class=\"col-12 col-lg-12\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                  <div class=\"col-lg-12 stretch-card\" style=\"padding: 0\">\r\n");
      out.write("                    <div class=\"card\">\r\n");
      out.write("                      <div class=\"card-body\">\r\n");
      out.write("                        <div\r\n");
      out.write("                          style=\"\r\n");
      out.write("                            display: flex;\r\n");
      out.write("                            align-items: center;\r\n");
      out.write("                            justify-content: space-between;\r\n");
      out.write("                          \"\r\n");
      out.write("                        >\r\n");
      out.write("                          <h4\r\n");
      out.write("                            class=\"card-title\"\r\n");
      out.write("                            style=\"margin-bottom: 0 !important\"\r\n");
      out.write("                          >\r\n");
      out.write("                            Giỏ hàng hiện tại\r\n");
      out.write("                          </h4>\r\n");
      out.write("                           <button style= \"margin-top: 20px;\" class = \"btn btn-success btn_thanhtoan\">Thanh toán ngay</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("						\r\n");
      out.write("						<div id = \"table_load\">\r\n");
      out.write("							<div class=\"table-responsive pt-3\">\r\n");
      out.write("                          	<table class=\"table table-bordered text-center\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <th>STT</th>\r\n");
      out.write("                                <th style = \"width: 100px\">Ảnh</th>\r\n");
      out.write("                                <th>Tên sách</th>\r\n");
      out.write("                                <th>Đơn giá</th>\r\n");
      out.write("                                <th style=\"width: 10%;\">Số lượng</th>\r\n");
      out.write("                                <th>Thành tiền</th>\r\n");
      out.write("                                <th>Chi tiết</th>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                          </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Xu ly phan trang -->\r\n");
      out.write("                          <div class=\"container\" style=\"margin-top:10px;display: flex;justify-content: center;align-items: center; flex-direction: column;\">\r\n");
      out.write("                            <div style=\"font-size: 20px; color: #C92127; font-weight: bold;\">Thành tiền: ");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write(" VND</div>\r\n");
      out.write("                         </div>\r\n");
      out.write("                        <!-- Ket thuc xu ly phan trang -->\r\n");
      out.write("						</div>\r\n");
      out.write("                        \r\n");
      out.write("                      </div>   \r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row display_none form_xacnhanmuahang\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"col-lg-12 stretch-card\" style=\"padding: 0\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <h4 class=\"card-title\" style=\"margin-bottom: 20px; text-align: center;\">\r\n");
      out.write("                                Thông tin mua hàng\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <div class=\"col-12\" style=\"display: flex; justify-content: center;\">\r\n");
      out.write("                                <div class=\"col-6\">\r\n");
      out.write("                                    <form action=\"");
      if (_jspx_meth_c_005furl_005f14(_jspx_page_context))
        return;
      out.write("\" id=\"form_checkout\">\r\n");
      out.write("                                        <div style=\"margin-bottom: 20px\">\r\n");
      out.write("                                        <label class=\"form-label\">Tên Khách Hàng</label>\r\n");
      out.write("                                        <input class=\"form-control showordisable\" name=\"fullname\" id = \"fullname\" type=\"text\" placeholder=\"Nhập tên khách hàng\">\r\n");
      out.write("                                        <p class = \"text-danger\" style=\"font-size: 14px;font-weight: bold; display:none;\">Họ tên không được rỗng</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div style=\"margin-bottom: 20px\">\r\n");
      out.write("                                        <label class=\"form-label\">Địa chỉ Email</label>\r\n");
      out.write("                                        <input class=\"form-control showordisable\" id = \"email\" name=\"email\" type=\"email\" placeholder=\"Nhập địa chỉ email\">\r\n");
      out.write("                                        <p class = \"text-danger\" style=\"font-size: 14px;font-weight: bold;display:none;\">Địa chỉ email không hợp lệ</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div style=\"margin-bottom: 20px\">\r\n");
      out.write("                                        <label class=\"form-label\">Số điện thoại</label>\r\n");
      out.write("                                        <input class=\"form-control showordisable\" name=\"phone\" id = \"phone\" type=\"number\" placeholder=\"Nhập số điện thoại\">\r\n");
      out.write("                                        <p class = \"text-danger\" style=\"font-size: 14px;font-weight: bold;display:none;\">Số điện thoại không hợp lệ</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div style=\"margin-bottom: 20px\">\r\n");
      out.write("                                        <label class=\"form-label\">Địa chỉ nhận hàng</label>\r\n");
      out.write("                                        <input class=\"form-control showordisable\" name=\"address\" id = \"address\" type=\"text\" placeholder=\"Nhập địa chỉ nhận hàng\">\r\n");
      out.write("                                        <p class = \"text-danger\" style=\"font-size: 14px;font-weight: bold; display:none;\">Địa chỉ không được rỗng</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                <div style=\"margin-bottom: 20px; text-align: center\">\r\n");
      out.write("                                  <button type=\"button\" class=\"btn btn-success btn_xacnhanmuahang\">Xác nhận đặt hàng</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </section>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    var toast_class = document.querySelector(\".toast_class\");\r\n");
      out.write("    var div = document.createElement(\"div\");\r\n");
      out.write("    \r\n");
      out.write("    function createToastHTML(message, type, color, icon){ //#47f764\r\n");
      out.write("		var toast_class = document.querySelector(\".toast_class\");\r\n");
      out.write("		var div = document.createElement(\"div\");\r\n");
      out.write("		var html = \"<div class = 'toast_to_left' style='position:relative; height: 90px;margin-bottom: 10px;'>\"+\r\n");
      out.write("    	    \"<div class='toast_container' style = 'border-left: 8px solid \"+color+\" !important;'>\"+\r\n");
      out.write("            \"<i class='\"+icon+\" toast_icon' style = 'color: \"+color+\" !important;'></i>\"+\r\n");
      out.write("            \"<div class='toast_content'>\"+\r\n");
      out.write("              \"<span style='font-weight: 700; color: \"+color+\";'>\"+type+\"</span>\"+\r\n");
      out.write("              \"<span class='toast_content_name' style='color: #656565'>\"+message+\"</span>\"+\r\n");
      out.write("           \" </div>\"+\r\n");
      out.write("            \"<div>\"+\r\n");
      out.write("              \"<i class='fa fa-times toast_close' style='font-size: 20px; cursor: pointer; color: #656565'aria-hidden='true'></i>\"+\r\n");
      out.write("            \"</div></div></div>\";\r\n");
      out.write("            div.innerHTML = html;\r\n");
      out.write("        toast_class.appendChild(div);\r\n");
      out.write("  		var toast_noi_dung = div.querySelector(\".toast_content_name\");\r\n");
      out.write("  	    var toast_container = div.querySelector(\".toast_container\");\r\n");
      out.write("  	    \r\n");
      out.write("			setTimeout(() => {\r\n");
      out.write("			    toast_container.classList.remove(\"toast_to_left\");\r\n");
      out.write("			    toast_container.classList.add(\"toast_to_right\");\r\n");
      out.write("			}, 2000);\r\n");
      out.write("			\r\n");
      out.write("			setTimeout(() => {\r\n");
      out.write("			    div.remove();\r\n");
      out.write("			}, 3000);\r\n");
      out.write("\r\n");
      out.write("		  	var toast_close = div.querySelector(\".toast_close\");\r\n");
      out.write("		  	console.log(toast_close);\r\n");
      out.write("		  	toast_close.addEventListener(\"click\", () => {\r\n");
      out.write("		    	div.remove();\r\n");
      out.write("		  	});\r\n");
      out.write("	}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    console.log(\"cart ban dau = \"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\r\n");
      out.write("    var cart_size = parseInt(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\r\n");
      out.write("    var btn_thanhtoan = document.querySelector(\".btn_thanhtoan\");\r\n");
      out.write("    var form_xacnhanmuahang = document.querySelector(\".form_xacnhanmuahang\");\r\n");
      out.write("    \r\n");
      out.write("    console.log(\"cart ban dau = \"+cart_size)\r\n");
      out.write("    if(cart_size == 0){\r\n");
      out.write("    	btn_thanhtoan.remove();\r\n");
      out.write("    	form_xacnhanmuahang.remove();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    	var edit_quanty_input;\r\n");
      out.write("    	\r\n");
      out.write("    	var result = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delete_result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    	if(result != \"\"){\r\n");
      out.write("	    	if(result == '0'){\r\n");
      out.write("		  		createToastHTML(\"Xóa không thành công do không tìm thấy ID sách\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '1'){\r\n");
      out.write("		  		createToastHTML(\"Xóa sách khỏi giỏ hàng thành công\", \"SUCCESS\", \"#47f764\", \"fas fa-check-circle\");\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	var result = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit_result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    	if(result != \"\"){\r\n");
      out.write("	    	if(result == '0'){\r\n");
      out.write("		  		createToastHTML(\"Số lượng sản phẩm không được nhỏ hơn 1\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '1'){\r\n");
      out.write("	    		createToastHTML(\"Không thể chỉnh sửa số lượng ID sách chưa tồn tại trong giỏ hàng\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '2'){\r\n");
      out.write("	    		createToastHTML(\"Số lượng nhập lớn hơn số lượng hiện có. Còn lại là ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${edit_conlai}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '3'){\r\n");
      out.write("		  		createToastHTML(\"Chỉnh sửa số lượng sản phẩm thành công\", \"SUCCESS\", \"#47f764\", \"fas fa-check-circle\");\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	var result = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${checkout_result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("    	if(result != \"\"){\r\n");
      out.write("    		if(result == '-1'){\r\n");
      out.write("	    		createToastHTML(\"Giỏ hàng của bạn đang trống, không thể thanh toán\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '0'){\r\n");
      out.write("	    		createToastHTML(\"Lỗi tạo Order đơn hàng\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '1'){\r\n");
      out.write("	    		createToastHTML(\"Lỗi tạo chi tiết đợn hàng\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}else if(result == '2'){\r\n");
      out.write("		  		createToastHTML(\"Chúc mừng, bạn đã mua hàng thành công!\", \"SUCCESS\", \"#47f764\", \"fas fa-check-circle\");\r\n");
      out.write("	    	}else{\r\n");
      out.write("	    		console.log(result);\r\n");
      out.write("	    		console.log(result.split(\" \"));\r\n");
      out.write("	    		myArray = result.split(\" \");\r\n");
      out.write("	    		for(var i = 0; i<myArray.length; i+=2){\r\n");
      out.write("	    			var bien = \".soluongconlai_\"+myArray[i];\r\n");
      out.write("	  		        var bien_html = document.querySelector(bien);\r\n");
      out.write("	  		        console.log(bien_html);\r\n");
      out.write("  		        	bien_html.innerHTML = \"Số lượng còn lại là: \"+ myArray[i+1];\r\n");
      out.write("  		        	bien_html.style.display = \"block\";\r\n");
      out.write("	    		}\r\n");
      out.write("	    		createToastHTML(\"Số lượng sản phẩm tồn kho không đủ số lượng bạn yêu cầu\", \"ERROR\", \"#DC3545\", \"fas fa-exclamation-triangle\");\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	var edit_quanty_input = document.querySelectorAll(\".edit_quanty_input\");\r\n");
      out.write("    	    edit_quanty_input.forEach((element) => {\r\n");
      out.write("    	        element.addEventListener(\"keypress\", (e) => {\r\n");
      out.write("    	          if ((e.which != 8 && e.which != 0 && e.which < 48) ||  e.which > 57) {\r\n");
      out.write("    	            e.preventDefault();\r\n");
      out.write("    	          }\r\n");
      out.write("    	        })\r\n");
      out.write("    	    })\r\n");
      out.write("    		\r\n");
      out.write("    	    edit_quanty_input.forEach((element) => {\r\n");
      out.write("    	      element.addEventListener(\"change\", (e) => {\r\n");
      out.write("    	         element.value = e.target.value;\r\n");
      out.write("    	         element.parentElement.submit();\r\n");
      out.write("    	      })\r\n");
      out.write("    	    });\r\n");
      out.write("    	                \r\n");
      out.write("    	             \r\n");
      out.write("    	\r\n");
      out.write("    	\r\n");
      out.write("    	// XU LY THANH TOÁN\r\n");
      out.write("        var reg_email = /^([A-Za-z0-9_\\-\\.])+\\@([A-Za-z0-9_\\-\\.])+\\.([A-Za-z]{2,4})$/;\r\n");
      out.write("        var reg_phone = /(03|05|07|08|09|01[2|6|8|9])+([0-9]{8})\\b/;\r\n");
      out.write("        var fullname = document.querySelector(\"#fullname\");\r\n");
      out.write("        var email = document.querySelector(\"#email\");\r\n");
      out.write("        var phone = document.querySelector(\"#phone\");\r\n");
      out.write("        var address = document.querySelector(\"#address\");\r\n");
      out.write("        \r\n");
      out.write("        fullname.addEventListener(\"input\", (e) => {\r\n");
      out.write("                fullname.value = e.target.value;\r\n");
      out.write("                if(fullname.value.trim().length == 0){\r\n");
      out.write("                    fullname.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("                    fullname.style.border = \"1px solid red\";\r\n");
      out.write("                }else{\r\n");
      out.write("                    fullname.parentElement.children[2].style.display = \"none\";\r\n");
      out.write("                    fullname.style.border = \"1px solid #dce7f1\";\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("         	email.addEventListener(\"input\", (e) => {\r\n");
      out.write("	            email.value = e.target.value;      \r\n");
      out.write("	            if(reg_email.test(email.value.trim()) == false){\r\n");
      out.write("	                email.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("	                email.style.border = \"1px solid red\";\r\n");
      out.write("	            }else{\r\n");
      out.write("	            	email.parentElement.children[2].style.display = \"none\";\r\n");
      out.write("	                email.style.border = \"1px solid #dce7f1\";\r\n");
      out.write("	            }\r\n");
      out.write("	        })\r\n");
      out.write("            \r\n");
      out.write("            phone.addEventListener(\"input\", (e) => {\r\n");
      out.write("            	phone.value = e.target.value;\r\n");
      out.write("                if(reg_phone.test(phone.value.trim()) == false || phone.value.trim().length !== 10){\r\n");
      out.write("                	phone.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("                	phone.style.border = \"1px solid red\";\r\n");
      out.write("                }else{\r\n");
      out.write("                	phone.parentElement.children[2].style.display = \"none\";\r\n");
      out.write("                	phone.style.border = \"1px solid #dce7f1\";\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            address.addEventListener(\"input\", (e) => {\r\n");
      out.write("            	address.value = e.target.value;\r\n");
      out.write("                if(address.value.trim().length == 0){\r\n");
      out.write("                	address.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("                	address.style.border = \"1px solid red\";\r\n");
      out.write("                }else{\r\n");
      out.write("                	address.parentElement.children[2].style.display = \"none\";\r\n");
      out.write("                	address.style.border = \"1px solid #dce7f1\";\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         function isValid(){\r\n");
      out.write("        	var check = true;\r\n");
      out.write("            if(fullname.value.trim().length == 0){\r\n");
      out.write("            	fullname.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("                fullname.style.border = \"1px solid red\";\r\n");
      out.write("                check = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if(reg_email.test(email.value.trim()) == false){\r\n");
      out.write("            	email.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("            	email.style.border = \"1px solid red\";\r\n");
      out.write("                check = false;\r\n");
      out.write("            }\r\n");
      out.write("            	\r\n");
      out.write("            if(reg_phone.test(phone.value.trim()) == false || phone.value.trim().length !== 10){\r\n");
      out.write("            	phone.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("            	phone.style.border = \"1px solid red\";\r\n");
      out.write("                check = false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if(address.value.trim().length == 0){\r\n");
      out.write("            	address.parentElement.children[2].style.display = \"block\";\r\n");
      out.write("            	address.style.border = \"1px solid red\";\r\n");
      out.write("            	check = false;\r\n");
      out.write("            }\r\n");
      out.write("            return check;\r\n");
      out.write("        }\r\n");
      out.write("            \r\n");
      out.write("		\r\n");
      out.write("       	btn_xacnhanmuahang = document.querySelector(\".btn_xacnhanmuahang\");\r\n");
      out.write("        var form_checkout = document.querySelector(\"#form_checkout\");\r\n");
      out.write("        btn_xacnhanmuahang.addEventListener(\"click\", () => {\r\n");
      out.write("        	if(isValid() === true){\r\n");
      out.write("        		form_checkout.submit();\r\n");
      out.write("        	}\r\n");
      out.write("        });\r\n");
      out.write("        	\r\n");
      out.write("        btn_thanhtoan.addEventListener(\"click\", () => {\r\n");
      out.write("       		form_xacnhanmuahang.classList.toggle(\"display_none\");\r\n");
      out.write("    	})\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    // COOKIE\r\n");
      out.write("    document.documentElement.scrollTop = getCookie(\"ScrollY\");\r\n");
      out.write("\r\n");
      out.write("     window.addEventListener(\"scroll\", () => {\r\n");
      out.write("        var x = pageYOffset;\r\n");
      out.write("        document.cookie = \"ScrollY=\"+x;\r\n");
      out.write("     });\r\n");
      out.write("\r\n");
      out.write("     function getCookie(cname) {\r\n");
      out.write("        let name = cname + \"=\";\r\n");
      out.write("        let decodedCookie = decodeURIComponent(document.cookie);\r\n");
      out.write("        let ca = decodedCookie.split(';');\r\n");
      out.write("        for(let i = 0; i <ca.length; i++) {\r\n");
      out.write("            let c = ca[i];\r\n");
      out.write("            while (c.charAt(0) == ' ') {\r\n");
      out.write("            c = c.substring(1);\r\n");
      out.write("            }\r\n");
      out.write("            if (c.indexOf(name) == 0) {\r\n");
      out.write("            return c.substring(name.length, c.length);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        return \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    	\r\n");
      out.write("	    \r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f15(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/account/cart.jsp(25,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/include/css/bootstrap.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/account/cart.jsp(26,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/include/css/toast.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/account/cart.jsp(27,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/include/css/app.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/account/cart.jsp(28,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/include/css/cart.css");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/views/account/cart.jsp(30,27) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/images/favico.png");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/views/account/cart.jsp(79,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/home.htm");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/views/account/cart.jsp(81,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/images/logo.png");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/views/account/cart.jsp(96,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/account/info.htm");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/views/account/cart.jsp(103,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/account/cart.htm");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /WEB-INF/views/account/cart.jsp(111,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/account/order.htm");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/account/cart.jsp(163,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/account/cart.jsp(163,28) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/account/cart.jsp(163,28) '${cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            	<tr class=\"table-white\">\r\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                 <td><img src=\"");
            if (_jspx_meth_c_005furl_005f10(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\" alt=\"\" style=\"height: 120px; width: auto\"/>\r\n");
            out.write("                                </td>\r\n");
            out.write("                                <td  class=\"cart_book_name\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.bookname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" đ</td>\r\n");
            out.write("                                <td>\r\n");
            out.write("                                	<form action=\"");
            if (_jspx_meth_c_005furl_005f11(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\" method =\"post\" class = \"form_edit\">\r\n");
            out.write("	                                	<input type=\"hidden\" name = \"bookid\" class=\"id_book_edit\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("	                                	<input style=\"text-align: center;\" min = \"1\" max = \"20\" class=\"form-control edit_quanty_input\" type=\"number\" name = \"quanty\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quanty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("	                                	<p class = \"text-danger soluongconlai_");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"font-size: 14px;font-weight: bold; display:none;\">Số lượng còn lại là: 0</p>\r\n");
            out.write("                                	</form>\r\n");
            out.write("                                </td>\r\n");
            out.write("                                <td>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" đ</td>\r\n");
            out.write("                                <td>\r\n");
            out.write("                                	<form action=\"");
            if (_jspx_meth_c_005furl_005f12(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\" method=\"post\" style=\"display: inline;\">\r\n");
            out.write("                                		<input type=\"hidden\" name = \"bookid\" value = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.product.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class = \"cart_delete\">\r\n");
            out.write("	                                    <button type = \"submit\" class=\"btn btn-danger btn_delete_cart\">Xóa</button>\r\n");
            out.write("									</form>\r\n");
            out.write("                                    <button class=\"btn btn-primary\"><a href=\"");
            if (_jspx_meth_c_005furl_005f13(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\" style = \"text-decoration:none; color:#fff\">Chi tiết</a></button>\r\n");
            out.write("                                </td>\r\n");
            out.write("                              </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/account/cart.jsp(166,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/images/${item.product.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/account/cart.jsp(171,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/book/edit.htm");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/account/cart.jsp(177,36) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("number");
      // /WEB-INF/views/account/cart.jsp(177,36) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("##,###");
      // /WEB-INF/views/account/cart.jsp(177,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.total_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/account/cart.jsp(179,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/book/delete.htm");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f13 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f13_reused = false;
    try {
      _jspx_th_c_005furl_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/account/cart.jsp(183,77) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f13.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/sach/${item.product.id}.htm", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f13 = _jspx_th_c_005furl_005f13.doStartTag();
      if (_jspx_th_c_005furl_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f13);
      _jspx_th_c_005furl_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f13, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /WEB-INF/views/account/cart.jsp(193,105) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setType("number");
      // /WEB-INF/views/account/cart.jsp(193,105) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("##,###");
      // /WEB-INF/views/account/cart.jsp(193,105) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f14 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f14_reused = false;
    try {
      _jspx_th_c_005furl_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f14.setParent(null);
      // /WEB-INF/views/account/cart.jsp(212,50) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f14.setValue("/checkout.htm");
      int _jspx_eval_c_005furl_005f14 = _jspx_th_c_005furl_005f14.doStartTag();
      if (_jspx_th_c_005furl_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f14);
      _jspx_th_c_005furl_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f14, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f15 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f15_reused = false;
    try {
      _jspx_th_c_005furl_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f15.setParent(null);
      // /WEB-INF/views/account/cart.jsp(498,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f15.setValue("/include/js/cart.js");
      int _jspx_eval_c_005furl_005f15 = _jspx_th_c_005furl_005f15.doStartTag();
      if (_jspx_th_c_005furl_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f15);
      _jspx_th_c_005furl_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f15, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f15_reused);
    }
    return false;
  }
}
